### ISSUE TITLE
[Webite] Vue Icon as Favicon

### ISSUE THREAD

**Issue by KBOE2** [smwbtech/vue-flash-message#12]
Is this wanted that you are using the Vue Logo https://smwbtech.github.io/vue-flash-message/favicon.ico as Favicon on https://smwbtech.github.io/vue-flash-message/ instead of the Vue-Flash-Message Logo?

Greetings Jan

**Comment by smwbtech** [comment]
@KBOE2 

Oh, thanks. :) I will change it with next patch commit. I get a little busy with my current work. Thank you for participation!

**Comment by smwbtech** [comment]
Fixed in 0.6.5 patch:
https://github.com/smwbtech/vue-flash-message/commit/baf5bb7361e82b81872526a9443020754cb29b05
