### ISSUE TITLE
Using h3 as tag for title

### ISSUE THREAD

**Issue by rcharre** [smwbtech/vue-flash-message#13]
Hello,

You are currently using a h3 tag to apply style on a text, this is against some a11y rules, you should probably replace it by a custom class styled text.

Regards,

**Comment by smwbtech** [comment]
Hi, @rcharre 

Thanks for recommendations! Yep, I guess it would be better solution, when I started this component I didn't think about accessibility. I finally got time for my open source projects, I guess in two weeks I'll release a new patch and include this changes.

**Comment by smwbtech** [comment]
Fixed in 0.6.5 patch:
https://github.com/smwbtech/vue-flash-message/commit/baf5bb7361e82b81872526a9443020754cb29b05
