### ISSUE TITLE
Clarify usage of component on SPC based apps

### ISSUE THREAD

**Issue by Peruibeloko** [smwbtech/vue-flash-message#2]
If you use this on SPC (Single Page Component) based apps, it **only** works if registered under your `main.js` file

There should be an observation noting this or a new way to use it as an import on a SPC

**Comment by smwbtech** [comment]
@Peruibeloko you are absolutly right. As far as I can understand your comment, in this version the only way to use this component is to register it in main.js (entry poitnt of the app). I will improve readme to make this aspect more obvious. 

Thanks ;)
