### ISSUE TITLE
Suggestion: Unescaped HTML or Component as message

### ISSUE THREAD

**Issue by KBOE2** [smwbtech/vue-flash-message#4]
Hey,
I found this great component today and I really like it. i've searched for a notification-component a lot and this is the one, i really want to use.
Well it would really help me if it was possible to disable the HTML-Escaping for messages. Another great feature would be giving a component as message. So the notification contains that and all the values are also updated.

It would also be pretty nice to have a flash message that does not hide automatically. For example by setting time to `0`.

Also the possibility to enable a progress bar that shows how long the message will still be there would be pretty nice.

Ok, I know this is more than just the title suggestion. I'm sorry 😁. But I would really like to see these features.

Greetings from Germany,
Jan :)

**Comment by smwbtech** [comment]
Hi @KBOE2! 

Thank you for your suggestions! I think that they are useful and will improve users experience. So i will add them to the plans. I had a lot stuff to do on my work after vacation, hope this weekend I can allocate time to make some of improvements!

Best regards, me :)

**Comment by KBOE2** [comment]
Thank you so much for implementing my wishes! 👍👍

On the website when selecting "Custom Component", there is a small bug in the Code.
In Line 17 it just says `component: 'CustomComponent',`. According to the Docs (and me testing that), `componentName: 'CustomComponent',` is the only working way.

**Comment by smwbtech** [comment]
Yep, You are absolutely right :)
