### ISSUE TITLE
Vuetify components issue

### ISSUE THREAD

**Issue by smwbtech** [smwbtech/vue-flash-message#5]
**Issue from Max**

Hello! im using vue-flash-message in all my apps and its great!
However, now when im using latest version of vuetify, the flash message popup is behind all vuetifys objects (buttons etc).

vue-flash-message used to work with vuetify.

It would be nice if you could look into that and see if you can fix it..

**Comment by mrkazu** [comment]
Hello! thank you for your response, i made custom css and imported it into vue

*custom.css
._vue-flash-msg-body {
    z-index: 3;
}

*main.js

**Comment by smwbtech** [comment]
@mrkazu 

Great! Glad to help you :)
