### ISSUE TITLE
html registration

### ISSUE THREAD

**Issue by amchconsult** [smwbtech/vue-flash-message#6]
Hi, 
Will you do an example registering the component in plain html?
Please

Thank you

**Comment by smwbtech** [comment]
Hi @amchconsult 

Not sure what do you mean about registration in plain HTML.
Could you provide a link to Vue docs with example or maybe some other project with the same case.

Best regards, me :)

**Comment by KBOE2** [comment]
Hey @amchconsult 

Do you mean like this: https://smwb-tech.gitbook.io/vue-flash-message/custom-component ? :)

( @smwbtech i think it is a bit confusing to have the links `custom-component` for html and `custom-comonent-1` for custom components )

Greetings
Jan

**Comment by amchconsult** [comment]
Hey,
I mean using it as CDN as global script tag.
Something like this:

```
<html>
<head>
  ...
</head>
<body>
  <div id="app">
    <flash-message></flash-message>
  </div>

  <script src="path/to/vue.js"></script>
  <script src="path/to/vue-flash-message.js"></script>
  <script>
    new Vue({
      el: '#app'
    })
  </script>
</body>
</html>
```

Thank you

**Comment by smwbtech** [comment]
Hi @amchconsult 

I created this JSFiddle [example](https://jsfiddle.net/romanprivalov/ykbwvpm8/19/)
Will this help to answer your question?

**Comment by smwbtech** [comment]
@KBOE2 

Thanks, I fix the slugs in documentation :)

**Comment by amchconsult** [comment]
Great, Thank you very much.
