### ISSUE TITLE
how to use it inside Vuex store

### ISSUE THREAD

**Issue by OmdaMukhtar** [smwbtech/vue-flash-message#7]
I am using vue-flash-message package like so :

main.js
```
import FlashMessage from '@smartweb/vue-flash-message';

Vue.use(FlashMessage, {
    name: 'flashMessage',
    tag: 'FlashMessage',
    time: 8000,
    strategy: 'single'
});
```

then inside vuex :
```
 this.flashMessage.success({
                title: 'Update Report ',
                message: 'Report daily Updated successfully'
            });
```
and get error like so :
```javascript
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'success' of undefined"

found in
```

 So can someone tell me what is going on!

**Comment by smwbtech** [comment]
Hi, @OmdaMukhtar 

Just get back from my winter holidays. So, sorry for late reply!

There are two several ways you can reach this.

1. You can access the Vue instance from vuex store with this._vm
More details in [codesandbox example](https://codesandbox.io/s/flamboyant-raman-17px2?fontsize=14&hidenavigation=1&theme=dark)

2. You can pass link to Vue instance as argument. [More details](https://github.com/vuejs/vuex/issues/1399#issuecomment-425331925)

Best regards,

**Comment by OmdaMukhtar** [comment]
Thanks, @smwbtech for helping me and I appreciate your consideration.
