### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by wubin1989** [smwbtech/vue-flash-message#8]
Hello,

The plugin is awesome! But I got a warning when I add it into my nuxtjs project.
`
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
`

**Comment by smwbtech** [comment]
@wubin1989 

Yep, I faced with the same problem, when using it in my own nuxt project.
The way I get over this issue <client-only> component. [More details](https://nuxtjs.org/api/components-client-only#the-lt-client-only-gt-component)

Is this acceptable to you?

**Comment by smwbtech** [comment]
So, I close this issue for now. 

If you will have problems, please, inform me.
